"""add password field

Revision ID: 15bcff34687e
Revises: 500d5f38d000
Create Date: 2013-11-24 23:40:00.193264

"""

# revision identifiers, used by Alembic.
revision = '15bcff34687e'
down_revision = '500d5f38d000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('password_hash', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastes', 'password_hash')
    ### end Alembic commands ###
