"""create attachments table

Revision ID: 17ca5ac43670
Revises: 89f9f6bc1a8
Create Date: 2014-01-06 05:13:56.919901

"""

# revision identifiers, used by Alembic.
revision = '17ca5ac43670'
down_revision = '89f9f6bc1a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('paste_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('saved_filename', sa.Text(), nullable=False),
    sa.Column('filetype', sa.Text(), nullable=False),
    sa.Column('preview_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paste_id'], ['pastes.paste_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    ### end Alembic commands ###
