"""empty message

Revision ID: 500d5f38d000
Revises: None
Create Date: 2013-11-24 23:37:11.946972

"""

# revision identifiers, used by Alembic.
revision = '500d5f38d000'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastes',
    sa.Column('paste_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('user_hash', sa.String(length=40), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=True),
    sa.Column('private_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['pastes.paste_id'], ),
    sa.PrimaryKeyConstraint('paste_id'),
    sa.UniqueConstraint('private_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastes')
    ### end Alembic commands ###
